/**
 * Mock provider — used when ANTHROPIC_API_KEY is not set (CI, demo
 * laptop, integration tests). The response is a deterministic,
 * rules-aware template so the system still "feels alive" in offline
 * contexts.
 *
 * Critically, the mock never invents content beyond the data it
 * receives in the system prompt. If the system prompt doesn't include
 * the data, the mock says so. This keeps the test surface honest.
 */
import type { ChatRequest, ChatResponse, LLMClient } from './client.js'

export class MockLLMClient implements LLMClient {
  readonly mode = 'mock' as const
  private defaultModel: string

  constructor(model: string = 'mock-narration-v1') {
    this.defaultModel = model
  }

  async chat(req: ChatRequest): Promise<ChatResponse> {
    // The mock just summarizes what was passed in. This is enough to
    // exercise the wiring (system + messages + ChatResponse shape) and
    // lets the integration test verify the LLM path runs end-to-end
    // without any network.
    const lastUser = [...req.messages].reverse().find((m) => m.role === 'user')?.content ?? ''
    const echo = [
      '[MOCK] This response was generated by the local mock LLM.',
      'Set ANTHROPIC_API_KEY to switch to the live Anthropic provider.',
      '',
      'System intent (truncated):',
      req.system.slice(0, 280).replace(/\n+/g, ' / '),
      '',
      'Your question was:',
      lastUser.slice(0, 280),
    ].join('\n')
    return {
      text: echo,
      model: this.defaultModel,
      usage: { inputTokens: 0, outputTokens: 0 },
      provider: 'mock',
    }
  }
}
